### ISSUE TITLE
[Feature Request] Could you add an option to log the response too? 

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [righettod/log-requests-to-sqlite#35]
Thanks for creating such a useful extension. Right now only request information is logged. If response is logged it will be more useful. For example I can use my custom program to process the logs. Could you add an option to log the response too? Thanks.

**Comment by righettod** [comment]
Hi,
Glad th head that the extension is helpful.
I will take a look at the possbility to add this option 😃

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the response! Yes, it is very useful! Thank again for creating this.

**Comment by righettod** [comment]
@seckek have implemented the feature 💯 

I have created this issue to track my work on the **2.0.0** that will include this feature: #47
