### ISSUE TITLE
Feature request : logfile configuration

### ISSUE THREAD

**Issue by vince-nayal** [righettod/log-requests-to-sqlite#6]
Hi Dominique,

First of all, thank you for this nice little plugin 👍 . I find it very useful for my assessments.

I'd like to submit to you two related feature requests regarding the plugin configuration : 

- [x] Add the ability to chose the sqlite file location
- [x] Add the ability to chose the sqlite filename

Kind regards

Vince

**Comment by righettod** [comment]
Tests OK. It's now possible to choose the location and the file name of the SQLite DB file.

**Comment by righettod** [comment]
You are welcome 👍 

Release of the v1.0.4 on BApp Store is on the way...

**Comment by Mincka** [comment]
Would it be possible to change the path from the menu?

**Comment by righettod** [comment]
Can you create a dedicated issue for the that enhancement for the tracking?
