### ISSUE TITLE
Chinese character garbled

### ISSUE THREAD

**Issue by feeops** [righettod/log-requests-to-sqlite#62]
open 
https://buff.163.com/

![screenshot](https://user-images.githubusercontent.com/92842117/156866348-89136d0f-9204-4029-bc69-b6a8f67ac07b.jpg)

Chinese character garbled when html charset=utf-8"

**Comment by feeops** [comment]
It is fixed.
Need add java -Dfile.encoding=UTF-8

**Comment by righettod** [comment]
Hi,
Thanks, I will add the jvm parameter directly in the extension loading code.
Thanks again for the issue and the solution.

**Comment by feeops** [comment]
> Hi, Thanks, I will add the jvm parameter directly in the extension loading code. Thanks again for the issue and the solution.

I am sorry.
It is work to burpsuite logger++ plugins
But it do not work to log-requests-to-sqlite plugins

**Comment by righettod** [comment]
I will ask to Burp team because, with the last version of Burp, Chinese characters of the test site are not correctly rendered:

![Test](https://user-images.githubusercontent.com/1573775/158540351-46c52752-e564-482f-8d04-4672858b9db5.png)

![Test2](https://user-images.githubusercontent.com/1573775/158540365-cb6362bc-77e6-4a34-abf7-8fc42824d58c.png)

**Comment by righettod** [comment]
Reply for the Burp team:

![image](https://user-images.githubusercontent.com/1573775/158566753-1f8c4c8d-e97f-4bb1-b156-b2496801dc62.png)

It will be fixed in next releases...

**Comment by righettod** [comment]
For Burp UI the solution was to change the *default font* to **Monospaced**:

![image](https://user-images.githubusercontent.com/1573775/158589337-94a59ecd-4316-4129-90ec-c8b821888740.png)

**Comment by feeops** [comment]
> For the Burp UI, the solution was to change the _default font_ to **Monospaced**:
> 
> ![image](https://user-images.githubusercontent.com/1573775/158589337-94a59ecd-4316-4129-90ec-c8b821888740.png)

I have change display font.It is ok in http message display.But It is not ok in sqlite.

**Comment by righettod** [comment]
Indeed, the fix at SQLite level will be done by the burp team because the
issue is located in the extension framework code present into burp.

**Comment by righettod** [comment]
Will be handled in #85
